### ISSUE TITLE
Simplify project structure and artifact naming

### ISSUE THREAD

**Issue by tzolov** [spring-projects-experimental/spring-ai-mcp#31]
Currently, our artifact and module naming is overly verbose and doesn't clearly reflect the project's structure and intended usage. We should simplify the naming scheme to make it more intuitive and better represent the distinct roles of each module.

#### Core SDK Module: `spring-ai-mcp-core` → `mcp`
- This rename better reflects the module's true purpose as a generic Java SDK for MCP
- Removes the `spring-ai` prefix since this module is intentionally Spring-independent
- Can be used by any Java application, not just Spring applications
- Provides core MCP functionality: client & server implementations, transports, etc.

#### Spring Integration Module: `spring-ai-mcp-spring` → `spring-ai-mcp`
- This module specifically provides Spring & Spring AI integration for MCP
- Keeps the `spring-ai` prefix as it's specifically for Spring AI integration
- Contains Spring-specific features like function calling integration
- Depends on the core `mcp` module but adds Spring-specific functionality

#### Parent Module: `spring-ai-mcp` → `mcp-parent`
- Better reflects its role as parent POM
- Follows common Maven naming patterns

### Tasks
- [x] Update module directory names
- [x] Update artifact IDs in all pom.xml files
- [x] Update module references in documentation
- [x] Update GitHub workflow for Maven Central release
- [x] Update import statements in example code
- [x] Update references in README files

### Benefits
- Clearer distinction between the generic Java SDK and Spring-specific integration
- Simpler, more intuitive artifact names
- Better aligned with standard Maven naming conventions
- Easier to maintain and understand project structure
- Makes it clearer that the core SDK can be used independently of Spring
- More accurate representation of each module's purpose and target audience

## Impact
This is a breaking change that will require users to update their dependencies in the next release.

This upgrade guide provides clear before/after examples and covers all the steps users need to take to adapt to the changes. It also includes verification steps and backwards compatibility information to help users plan their upgrade strategy.

### For Core MCP SDK Users
If you're using just the core MCP functionality:

```xml
<!-- Replace this -->
<dependency>
    <groupId>org.springframework.experimental</groupId>
    <artifactId>spring-ai-mcp-core</artifactId>
    <version>0.1.0</version>
</dependency>

<!-- With this -->
<dependency>
    <groupId>org.springframework.experimental</groupId>
    <artifactId>mcp</artifactId>
    <version>0.2.0</version>
</dependency>
```

If you're using the Spring AI integration:

```xml
<!-- Replace this -->
<dependency>
    <groupId>org.springframework.experimental</groupId>
    <artifactId>spring-ai-mcp-spring</artifactId>
    <version>0.1.0</version>
</dependency>

<!-- With this -->
<dependency>
    <groupId>org.springframework.experimental</groupId>
    <artifactId>spring-ai-mcp</artifactId>
    <version>0.2.0</version>
</dependency>
```
